data:
  sources:
    - type: csv
      path: data/serialized/dataset_1.csv
    - type: csv
      path: data/serialized/dataset_2.csv
    - type: csv
      path: data/serialized/dataset_3.csv

  target_column: popularity
  timestamp_column: release_date

logger:
  log_file: logs/log.txt
  log_level: INFO

collection:
  batch_size: 1024

storage:
  type: postgres

  postgres:
    host: localhost
    port: 5432
    database: mlops
    user: YOUR_USERNAME
    password: YOUR_PASSWORD

cleaning:
  max_row_missing: 0.1

analysis:
  reports_dir: eda_plots