data:
  sources:
    - type: csv
      path: data/train/dataset_1.csv
    - type: csv
      path: data/train/dataset_2.csv
    - type: csv
      path: data/train/dataset_3.csv

  target_column: popularity
  timestamp_column: release_date

logger:
  log_file: logs/log.txt
  log_level: INFO

collection:
  batch_size: 1024

storage:
  type: postgres

  postgres:
    host: localhost
    port: 5432
    database: mlops
    user: mluser
    password: mlpass

cleaning:
  max_row_missing: 0.1

analysis:
  reports_dir: eda_plots

model:
  streaming_model:
    window_size: 5000
    prune_every: 300
    min_models: 1
    save_path: "models/streaming_ensemble.pkl"
    
  model_grid:

    variants:
      - {lr: 0.0005, reg_type: l2, reg: 0.0001}
      - {lr: 0.001,  reg_type: l2, reg: 0.001}
      - {lr: 0.003,  reg_type: l2, reg: 0.001}
      - {lr: 0.005,  reg_type: l2, reg: 0.01}
      - {lr: 0.01,   reg_type: l2, reg: 0.01}
      - {lr: 0.02,   reg_type: l2, reg: 0.05}

      - {lr: 0.0005, reg_type: l1, reg: 0.0001}
      - {lr: 0.001,  reg_type: l1, reg: 0.001}
      - {lr: 0.003,  reg_type: l1, reg: 0.001}
      - {lr: 0.005,  reg_type: l1, reg: 0.01}
      - {lr: 0.01,   reg_type: l1, reg: 0.01}
      - {lr: 0.02,   reg_type: l1, reg: 0.005}
  
  feature_combinations:
    - ["num"]
    - ["num", "artists"]
    - ["num", "artists", "names"]
  
  training:
    validation_split: 0.8
    random_state: 42
    verbose: true